lib/cb/version.rb
lib/tasks/doc.rake

Super tiny PR - previously the `doc:generate` task would not show up with `rake -T`. Now it does - apparently all it needs is a description. This was discovered via https://github.com/cbdr/ruby-cb-api-internal/pull/110.

doc task now shows up with rake -T

---

CHANGELOG.md
lib/cb/models/implementations/resumes/salary_information.rb
lib/cb/models/implementations/resumes/work_experience.rb
lib/cb/version.rb
spec/cb/models/implementations/resume/resume_spec.rb
spec/support/response_stubs/resume_get.json

To Test:
copy and paste the following (after changing out the dev_key/ resume_hash/ user_id for your own)
--------------------------------------------------
bundle exec pry
Cb.configure do |config|
config.dev_key    = 'dev_key'
config.time_out  = 30
config.debug_api  = true
end
request = Cb::Requests::Resumes::Get.new( {resume_hash: 'resume_hash', external_user_id: 'user_id'})
client = Cb::Client.new
response = client.execute request
----------------------------------------------------
you should see that the work experiences now have a node "id", and that Salary information does not have job title any more, but does have "workExperienceId"

making the changes to match the resume API

---

CHANGELOG.md
lib/cb/exceptions.rb
lib/cb/utils/validator.rb
lib/cb/version.rb
spec/cb/utils/validator_spec.rb

401 responses will now throw out an UnauthorizedError. This will allow handling and recovering this specific response down the line.

Added support for handling 401 unauthorized errors.

---

CHANGELOG.md
lib/cb/requests/resumes/put.rb
lib/cb/version.rb
spec/support/mocks/resume.rb

Adding support for work experience ID in place of "job title" in the salary section of resume.
Also adding work experience ID as a field in the work experience section of resume.
https://careerbuilder.mingle.thoughtworks.com/projects/job_discovery_ux__search___re/cards/768

Api changes for work experience id

---

CHANGELOG.md
lib/cb/responses/errors.rb
lib/cb/version.rb
spec/cb/responses/errors_spec.rb

I want to propose a change to the @parsed variable. Currently if there is an api response error we create the message using the to_s method on the hash/array. 
This returns an ugly string i.e. "[\"File upload data is larger than the maximum of 1024KB.\"]"
I changed it to join(',')  which will now return 'File upload data is larger than the maximum of 1024KB.'
If there is an array such as [much, awesome, so api, wow]
it will now return  'much awesome,so api,wow'
we are currently doing some message conversion and translation and instead of regexing this in our app I thought it would be more elegant to do this in the error class. Thoughts?

Error response

---

README.md

I have updated the README file so that it correctly outlines the process of performing a job search.
I have also included job accessor methods and search params.
Please note: I was given a list of available search params which I included. It does not appear that the list is complete. If you have a complete list I can update the pull request.

Overhaul Readme to include correct job searching

---

CHANGELOG.md
lib/cb/requests/resumes/delete.rb
lib/cb/requests/resumes/get.rb
lib/cb/requests/resumes/language_codes.rb
lib/cb/requests/resumes/post.rb
lib/cb/requests/resumes/put.rb
lib/cb/version.rb
spec/cb/requests/resumes/delete_spec.rb
spec/cb/requests/resumes/get_spec.rb
spec/cb/requests/resumes/language_codes_spec.rb
spec/cb/requests/resumes/post_spec.rb
spec/cb/requests/resumes/put_spec.rb

Versioning in the new APIs is via header and its assumed that if you dont ask for a version you always get latest.  I am changing the format of the APIs a lot so I'm pegging us at the old format until such time I can convert our calls.

Pegging us at 1.0 of webapi resume 

---

CHANGELOG.md
lib/cb/models/api_call_model.rb
lib/cb/utils/api.rb
lib/cb/version.rb
spec/cb/utils/api_spec.rb
spec/support/mocks/observer.rb

Lay the groundwork for starting to collect API call timings via our existing observers like https://github.com/cbdr/consumer-main/blob/master/config/initializers/cb_api.rb#L26-L48 and https://github.com/cbdr/consumer-domain/blob/master/lib/rails/cb_api_observer.rb

Add API timings to observers

---

CHANGELOG.md
lib/cb/utils/validator.rb
lib/cb/version.rb
spec/cb/utils/validator_spec.rb

Exactly what the title says: with this PR, you'll be able to set an environment variable to cause all API calls to throw a `Cb:: ServiceUnavailableError` error. 
To do it:
```ruby
ENV['SIMULATE_AUTH_OUTAGE'] = 'true'
```
```bash
SIMULATE_AUTH_OUTAGE=true
```

Simulate auth outage

---

CHANGELOG.md
lib/cb/clients/job.rb
lib/cb/config.rb
lib/cb/models/implementations/job_results_v3.rb
lib/cb/requests/job_search/get.rb
lib/cb/responses/job/search_v3.rb
lib/cb/utils/response_map.rb
lib/cb/version.rb
spec/cb/models/implementations/job_results_v3_spec.rb
spec/cb/responses/job/search_v3_spec.rb
spec/support/response_stubs/company_colapse_search_result_v3.yml
spec/support/response_stubs/search_result_v3.yml

This adds v3 of the job search api to the library.  According to the search team there may be differences between the jobs returned.  We want to be able to quickly switch between calls to the v3 and v2 in case there are site performance issues.  To do this we believe both the v2 and v3 searches should be in the gem and higher level logic will make the determination of which to call.

Add jobsearch v3

---

.rubocop.yml
CONTRIBUTING.md
LICENSE
NOTICE
README.md
Rakefile
cb-api.gemspec

Add license, notice, contributing guide, our rubocop defaults and updates the readme a bit.  Also makes clear that the license is apache (we never really declared one before but we had the gemspec set to MIT)

First PR towards open sourcing this under the new account

---

README.md
cb-api.gemspec
spec/spec_helper.rb

Adds the code climate badges and the code climate reporter so we can actually send them our code coverage numbers.  Build is already setup to do so but we didn't include this gem.

Transfer ownership

---

CHANGELOG.md
lib/cb/utils/api.rb
lib/cb/version.rb
spec/cb/utils/api_spec.rb

Today we are collecting API timings, but have instances in our code where we are calling through the additional `lib/cb/client.rb` that exists in this project. This is not useful to us, so we are going to dig a level beyond that file to see who's calling it.
Also move the observer notification to a `begin...ensure` block to avoid losing the timings around errors. This is still valuable information to know and should impact our API timings dashboard numbers.

Improve timing collection and granularity

---

CHANGELOG.md
lib/cb/client.rb
lib/cb/utils/api.rb
lib/cb/version.rb
spec/cb/client_spec.rb
spec/cb/utils/api_spec.rb

`execute_http_request` -> `timed_http_request` for better naming of what the method's responsibilities are. Also broke out the actual execution of the http request from the `timed_http_request` method for clarity.

Method renaming

---

CHANGELOG.md
lib/cb/clients/recommendation.rb
lib/cb/version.rb
spec/cb/clients/recommendation_spec.rb

This fixes the similar jobs for company function. If you want to reproduce this problem, simply put a breakpoint and examine 'json_hash'. You will see that this is needed.
What caused this find was using the 'employer/jobrecommendation' endpoint on branded JDP's for similar jobs.

Similar jobs company

---

CHANGELOG.md
lib/cb/clients/recommendation.rb
lib/cb/version.rb

By doing this, we avoid fighting with nil checking. This does end up doing some data coercion though, so if the API was failing and returning empty for one of these keys consistently, we wouldn't see that by handling the API response this way.

Use chained fetch instead of nested if statements

---

CHANGELOG.md
lib/cb/clients/recommendation.rb
lib/cb/version.rb
spec/cb/clients/recommendation_spec.rb

````
[3] pry(Cb::Clients::Recommendation)> json_hash
=> {"Results"=>{"JobRecommendation"=>{"Jobs"=>nil}}}
[4] pry(Cb::Clients::Recommendation)> json_hash.fetch('Results', {}).fetch('JobRecommendation', {}).fetch('Jobs', {}).fetch('CompanyJob', []).each
NoMethodError: undefined method `fetch' for nil:NilClass
from (pry):4:in `for_company'
````

fix nil jobs returned from api

---

CHANGELOG.md
lib/cb/clients/recommendation.rb
lib/cb/version.rb
spec/cb/clients/recommendation_spec.rb

We were receiving the following error: ***TypeError: no implicit conversion of String into Integer***
Here is the json response we were getting on the ***error*** page:
````
{"Results"=>
{"JobRecommendation"=>
{"Jobs"=>
{"CompanyJob"=>
{"JobDID"=>"JHR5RK7870G6J01G6CZ", "JobLink"=>"/JobSeeker/Jobs/JobDetails.aspx?job_did=JHR5RK7870G6J01G6CZ", "JobTitle"=>"IT Technician", "Industries"=>{"string"=>"Retail"}, "Location"=>"US-GA-Atlanta", "Source"=>nil, "Date"=>"2015-10-29T08:17:27.423"}}}}}
````
We take the ````CompanyJob```` node and ````.each```` through it. Notice that this is NOT AN ARRAY so when we would loop through it, we would not pass the entire Job to  ````Models::Job````. Pages that work correctly return an array of jobs.
***Solution***: We are going to see if it is an array, and …

Handle job response

---

CHANGELOG.md
lib/cb/models/implementations/resume_listing.rb
lib/cb/version.rb
spec/cb/models/implementations/resume_listing_spec.rb

To use the new Resume API in c-m, we need the current get list API to return the migration ID of the requested resume so that GRRP can use the correct ID when calling retrieve since, initially, it will not use the new get list API. The change to send the migration ID back has been made on the matrix and is flag wrapped
If the migration ID exists, it means the resume has been migrated to the new service and that ID should be used when requesting the resume from the new service. 
If no migration ID is present, the external id should be used. That will trigger the new service to pull the resume over from the matrix.

Add migration id to list model

---

CHANGELOG.md
lib/cb/clients/anon_saved_search.rb
lib/cb/clients/application.rb
lib/cb/clients/application_external.rb
lib/cb/clients/base.rb
lib/cb/clients/category.rb
lib/cb/clients/company.rb
lib/cb/clients/cover_letters.rb
lib/cb/clients/education.rb
lib/cb/clients/employee_types.rb
lib/cb/clients/industry.rb
lib/cb/clients/job_branding.rb
lib/cb/clients/recommendation.rb
lib/cb/clients/saved_search.rb
lib/cb/clients/talent_network.rb
lib/cb/clients/user.rb
lib/cb/config.rb
lib/cb/convenience.rb
lib/cb/utils/api.rb
lib/cb/utils/nil_response.rb
lib/cb/version.rb
spec/cb/clients/anon_saved_search_spec.rb
spec/cb/clients/application_external_spec.rb
spec/cb/clients/company_spec.rb
spec/cb/clients/cover_letters_spec.rb
spec/cb/clients/education_spec.rb
spec/cb/clients/employee_types_spec.rb
spec/cb/clients/saved_search_spec.rb

Refactoring of the clients.  Breaking changes to AnonSavedSearch, EmployeeTypes, SavedSearch because they were switched to class methods instead of instance methods in order to match the other old style clients.
New coverletters api works like this:
List all coverletters 
```ruby
Cb.cover_letters.get(oauth_token: token)
```
Retrieve one coverletter 
```ruby
Cb.cover_letters.get(id: 'CLXXXXXXXXXXXXXX', oauth_token: token)
```
Create one coverletter
```ruby
Cb.cover_letters.create(name: 'name 1', text: 'text 1', oauth_token: token)
```
Update coverletter 
```ruby
Cb.cover_letters.update(id:'CXXXXXX'; name: 'name 1', text: 'text 1', oauth_token: token)
```
Delete coverletter 
```ruby
Cb.cover_letters.delete(id:'CXXXXXX', oauth_token: token)
```

Dont Merge: Refactoring of the old clients, add new coverletter endpoint

---

CHANGELOG.md
lib/cb/models/implementations/resume_listing.rb
lib/cb/version.rb
spec/cb/models/implementations/resume_listing_spec.rb

We no longer need the migration ID to be passed through. Removing it.

Revert resume list changes

---

CHANGELOG.md
lib/cb/utils/nil_response.rb
lib/cb/version.rb

With ruby 2.2 we can no longer mess with Nil since it is frozen so we instead choose to send a fake nil that is patched.  This makes it behave a bit more like it did pre ruby 2.2 so we don't get errors like this when the API fails to return us the model we were looking for

trying not to break peeeps

---

CHANGELOG.md
lib/cb/models/implementations/job.rb
lib/cb/version.rb
spec/cb/models/implementations/job_spec.rb
spec/support/response_stubs/recommendations_for_job.json

We are adding 'posting_date' to the job model for when we get recommendations for a job.
````
"PostingDate": "2/19/2016 12:00:00 AM",
`````
We had three options:
1. Add 'posting_date' to the existing job model that is passed to the consuming app.
2. Use new recs api instead and make sure to include 'posting_date'.
3. Rearchitect the API to pass the response hash, and then handle all the mappings in the consuming app. 
We ended up going with option 1 because it would be a quick turn around to deliver value of moving forward towards the migration of Matrix to GRRP. We would like to push the pulling through of any new implementations/recs version upgrade since we are able to accomplish what we need by a few simple changes.

Add posting_date to job model

---

CHANGELOG.md
lib/cb/clients/saved_jobs.rb
lib/cb/config.rb
lib/cb/convenience.rb
lib/cb/version.rb
spec/cb/clients/saved_jobs_spec.rb

As the name implies
```ruby
saved_jobs = Cb.saved_jobs.get({ site: host_site, oauth_token: access_token })['data']
```

New Saved Jobs API

---

CHANGELOG.md
lib/cb/utils/validator.rb
lib/cb/version.rb
spec/cb/utils/validator_spec.rb

We get a bunch of `Cb::ServerError`s with the message also set to `Cb::ServerError`, which isn't helpful. New Relic cannot group errors with them all set to this. This is an attempt to fix that, at least for the APIs that follow the standard (uses an 'errors' node which is an array of strings).

Add error message to error raised from API

---

CHANGELOG.md
lib/cb/utils/validator.rb
lib/cb/version.rb
spec/cb/utils/validator_spec.rb

This handles comments from https://github.com/careerbuilder/ruby-cb-api/pull/253 that included following our style guide more closely and returning the empty string when there is no errors node available in the error that we got back from the API.

Use `.first` and return emtpy string when no errors node

---

CHANGELOG.md
lib/cb/models/implementations/job.rb
lib/cb/version.rb
spec/cb/models/implementations/job_spec.rb

Presently the gem does not have accessors for this data it is already getting back from the API.  We need these fields to correct the posted within field on the new JDP.  Part of effort to fix CSI280515.

Add Begin and End Date Times to Job

---

CHANGELOG.md
lib/cb/version.rb
spec/cb/clients/user_spec.rb

Update test for compatibility with Ruby 2.3.1. `ArgumentError`'s error message changed from "wrong number of arguments (0 for 1)" to "wrong number of arguments (given 0, expected 1)" in Ruby 2.3.0.

Ruby 2.3.1

---

CHANGELOG.md
lib/cb/clients/base.rb
lib/cb/utils/api.rb
lib/cb/version.rb

This change will allow implementers to pass headers into the instantiation.  Please see the following example.
```Ruby
class TestClass < Base
def TestClass.headers
{ accept: 'application/json' }
end
def TestClass.get
cb_client(headers: headers)
...
end
end
```

Configure headers

---

CHANGELOG.md
lib/cb/clients/recommendations.rb
lib/cb/version.rb
spec/cb/clients/recommendations_spec.rb

Adds new client to return User and Job recommendations in a hash with the recid (and other metadata). We need this RecID field to start doing NDCG on recs calls.
Done side by side with existing code (which is in the poorly name Recommendation class) for a transition and to avoid the major version bump.

Recommendations client

---

CHANGELOG.md
lib/cb/clients/job.rb
lib/cb/version.rb
spec/cb/clients/job_spec.rb

So cool story. Not pushing the Job hash through the models skipped some error checking and throwing.  Added that back in.
After discussions with Jeff/Colin.  We decided to throw the 404 DocumentNotFoundError since the api should be returning 404 instead of 200.  Going to put in an AO ticket to have that api changed.

Adding back error checking and throwing on Job call

---

lib/cb/clients/recommendations.rb
spec/cb/clients/recommendations_spec.rb

Previous system used a bunch of `if hash.key? :key_name` nested 7 layers deep. I switched to `dig` then reverted to hash access for pre-2.3 compatibility.
This just rescues the NoMethodError from trying to build. Any exception here should really go to `[]`, but I figured on the smallest scope of change for now.

Fix recs NoMethodError for no-recs errors.

---

CHANGELOG.md
lib/cb/clients/email_subscriptions.rb
lib/cb/clients/job.rb
lib/cb/clients/job_search.rb
lib/cb/clients/resumes.rb
lib/cb/version.rb
spec/cb/clients/email_subscriptions_spec.rb
spec/cb/clients/job_search_spec.rb
spec/cb/clients/job_spec.rb
spec/cb/clients/resumes_spec.rb

Adds clients alongside existing Request-type APIs. Goal here is to add them alongside for an easy transition, saving a major version bump w/ removal for when GRRP is no longer using it.

Migrate more calls to clients

---

lib/cb/models/implementations/saved_search.rb
spec/cb/clients/saved_search_spec.rb
spec/cb/models/implementations/saved_search_spec.rb

Turns out there is a place (JRP) where you can set the frequency before saving the search. So we need these guys as part of the request.

Adding nodes back to create

---

CHANGELOG.md
lib/cb/clients/resumes.rb
lib/cb/version.rb
spec/cb/clients/resumes_spec.rb

We added functionality to the update call on resume in the matrix to accept resumeFileData, resumeFileName, and replaceEducationAndExperience.  This PR adds these fields to the put request for GRRP.

Replace resume

---

CHANGELOG.md
lib/cb/requests/resumes/put.rb
lib/cb/version.rb
spec/support/mocks/resume.rb

We added functionality to the update call on resume in the matrix to accept resumeFileData, resumeFileName, and replaceEducationAndExperience.  This PR adds these fields to the put request for GRRP.

Replace Resume Fields Part Duex

---

CHANGELOG.md
lib/cb/clients/base.rb
lib/cb/utils/api.rb
lib/cb/version.rb
spec/cb/api_spec.rb

Mahoneys team wants us to stop adding developerkey and outputjson to the url of the geo validation calls. My solution to this is to add an optional argument that defaults to true so that everything continues to work as normal. We can initialize the client in the geo client with 'use_default_params: false' so that it does not add these.
http://insights-1.cbmtn.io/insights/assistant-store-manager?location=houston,tx

Optionally Add Default Params

---

CHANGELOG.md
lib/cb/clients/base.rb
lib/cb/version.rb
spec/cb/clients/base_client_spec.rb

This PR adds an optional parameter to the `Cb::Clients::Base.headers` method to allow overriding of the Accept header. 
It still defaults to the old value (application/json), but now if you pass in the kwarg `:accept_header` the headers that are returned will contain the value of the kwarg for the Accept header. The base client didn't have any tests so I did a quick, cheesy test for the `cb_client` method and then some more in depth tests that assert how the `headers` method works.

Allow optional Accept header

---

CHANGELOG.md
lib/cb/models/implementations/saved_search.rb
lib/cb/version.rb
spec/cb/models/implementations/saved_search_spec.rb

Super simple - adding a supported field to the XML we send to Anonymous Saved Search (`/v1/anonymoussavedjobsearch/create/`).
This field is optional so sending empty here is no issue.

add SiteID to XML sent to Anon Saved Search API

---

lib/cb/clients/job.rb
lib/cb/version.rb
spec/cb/clients/job_spec.rb

- changes `Cb::Clients::Job.get` to include oauth token as a parameter
- updates specs to pass in oauth token
- bump major version as this changes the method signature

add oauth token as param for retrieval of job, bump major version

---

CHANGELOG.md
lib/cb/clients/job.rb
lib/cb/config.rb
lib/cb/version.rb
spec/cb/clients/job_spec.rb

This argument will determine which route to use for job details retrieval.  The argument defaults to false and will use the consumer/job/details endpoint by default. If you set the argument to true it will use the v3/job endpoint.

Adding parameter to job get
